//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCV.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMe
    {
        public byte ID { get; set; }
        public string NAME { get; set; }
        public string SURNAME { get; set; }
        public string myDESC { get; set; }
    }
}
