//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCV.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSite
    {
        public byte id { get; set; }
        public string SITENAME { get; set; }
        public string SITEDESC { get; set; }
        public string FOOTER { get; set; }
    }
}
